volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    # To run Kestra in a rootless mode in production, see: https://kestra.io/docs/installation/podman-compose
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      KESTRA_PLUGINS: 'io.kestra.plugin.scripts,io.kestra.plugin.otherplugin, io.kestra.plugin.scripts.shell.commands, io.kestra.plugin.scripts.python.Commands'
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basicAuth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          defaults:
            - type: io.kestra.plugin.jdbc.postgresql
              values:
                url: jdbc:postgresql://host.docker.internal:5432/kestra
                username: kestra
                password: k3str4
            - type: io.kestra.plugin.jdbc.postgresql.Queries
              values:
                url: jdbc:postgresql://host.docker.internal:5432/kestra
                username: kestra
                password: k3str4
                
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started


  postgres_db:
    image: postgres
    container_name: postgres-data
    environment:
      POSTGRES_USER: ny_taxi_user
      POSTGRES_PASSWORD: ny_taxi_user_password
      POSTGRES_DB: ny_taxi
      TZ: America/New_York
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    depends_on:
      kestra:
        condition: service_started


  pgadmin-service:
    image: dpage/pgadmin4
    container_name: pgadmin_kestra
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    ports:
      - "18080:80"
    volumes:
      - ./pgdata:/var/lib/pgadmin
    depends_on:
      postgres_db:
        condition: service_started


